import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/providers/session-provider";
import NextUiProviders from "@/providers/nextui-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className="w-full">
          <NextUiProviders>
            {children}
          </NextUiProviders>
        </body>
      </html>
    </SessionProvider >
  );
}
